services:
    wordpress:
            build: ./requirements/wordpress/
            image: wordpress:inception
            container_name: wordpress
            volumes:
                    - wordpress-data:/var/www/wordpress
            networks:
                    - inception
            depends_on:
                mariadb:
                    condition: service_healthy
            environment:
                    - MYSQL_DATABASE
                    - MYSQL_USER
                    - MYSQL_PASSWD
                    - MYSQL_ROOT_PASSWD
                    - DOMAIN_NAME
                    - MYSQL_HOST
                    - COMMON_USER
                    - COMMON_EMAIL
                    - COMMON_PASS
    nginx:
            build: ./requirements/nginx/
            image: nginx:inception
            container_name: nginx
            ports: 
                    - 443:443
            networks:
                    - inception
            depends_on:
                    - wordpress
            volumes:
                - wordpress-data:/var/www/wordpress
    mariadb:
            build: ./requirements/mariadb/
            image: mariadb:inception
            container_name: mariadb
            networks:
                    - inception
            environment:
                    - MYSQL_USER
                    - MYSQL_PASSWD
                    - MYSQL_DATABASE
                    - DOMAIN_NAME
                    - MYSQL_ROOT_PASSWD
            healthcheck:
                test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWD}"]
                interval: 5s
                timeout: 5s
                retries: 7
            volumes:
                    - mariadb-data:/var/lib/mysql

volumes:
    wordpress-data:
            name: wordpress-data
            driver: local
            driver_opts:
                o: bind
                type: none
                device: /home/marcrodr/data/wordpress
    mariadb-data:
            name: mariadb-data
            driver: local
            driver_opts:
                o: bind
                type: none
                device: /home/marcrodr/data/mariadb

networks:
    inception:
            driver:
                bridge
