services:
    wordpress:
            build: ./requirements/wordpress/
            container_name: wordpress
            volumes:
                    - wordpress-data:/var/www/wordpress
            networks:
                    - inception
            depends_on:
                mariadb:
                    condition: service_healthy
            env_file:
                .env
    nginx:
            build: ./requirements/nginx/
            container_name: nginx
            ports: 
                    - 443:443
            networks:
                    - inception
            depends_on:
                    - wordpress
            volumes:
                - wordpress-data:/var/www/wordpress
    mariadb:
            build: ./requirements/mariadb/
            container_name: mariadb
            networks:
                    - inception
            env_file:
                .env
            healthcheck:
                test: mysqladmin ping -h localhost -u$MYSQL_USER -p$MYSQL_ROOT_PASSWD
                interval: 5s
                timeout: 5s
                retries: 7
volumes:
    wordpress-data:
    mariadb-data:

networks:
    inception:
            driver:
                bridge
