services:
    wordpress:
            build: ./requirements/wordpress/
            container_name: wordpress
            volumes: 
                    - wordpress-data:/var/www/wordpress
            networks:
                    - inception
            depends_on:
                    - mariadb
            env_file:
                .env # file with enviroment variables
    nginx:
            build: ./requirements/nginx/
            container_name: nginx
            ports: 
                    - 443:443
            networks:
                    - inception
            depends_on:
                    - wordpress
    mariadb:
            build: ./requirements/mariadb/
            container_name: mariadb
            networks:
                    - inception
            env_file:
                .env
volumes:
    wordpress-data:
networks:
    inception:
        driver:
            bridge
